# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_schedule2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule2',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='TIME',
            field=models.TimeField(),
        ),
    ]
